### ISSUE TITLE
Something fishy with the redis connection

### ISSUE THREAD

**Issue by sandbergja** [lbcclib/community_archive#75]
the hyrax pod is reporting:

```
#<Thread:0x000055bb680f98e8 /usr/local/bundle/gems/actioncable-5.2.6/lib/action_cable/subscription_adapter/redis.rb:148 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:229:in `getaddrinfo': getaddrinfo: Name does not resolve (SocketError)
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:229:in `connect'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:313:in `connect'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:336:in `establish_connection'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:101:in `block in connect'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:293:in `with_reconnect'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:100:in `connect'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:276:in `with_socket_timeout'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:133:in `call_loop'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis/subscribe.rb:43:in `subscription'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis/subscribe.rb:12:in `subscribe'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:2775:in `_subscription'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:2143:in `block in subscribe'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:58:in `block in synchronize'
        from /usr/local/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
        from /usr/local/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:58:in `synchronize'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:2142:in `subscribe'
        from /usr/local/bundle/gems/actioncable-5.2.6/lib/action_cable/subscription_adapter/redis.rb:81:in `block in listen'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:293:in `with_reconnect'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:64:in `block in with_reconnect'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:58:in `block in synchronize'
        from /usr/local/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
        from /usr/local/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:58:in `synchronize'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:63:in `with_reconnect'
        from /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:70:in `without_reconnect'
        from /usr/local/bundle/gems/actioncable-5.2.6/lib/action_cable/subscription_adapter/redis.rb:78:in `listen'
        from /usr/local/bundle/gems/actioncable-5.2.6/lib/action_cable/subscription_adapter/redis.rb:152:in `block in ensure_listener_running'
```

**Comment by sandbergja** [comment]
47af680222d3cb03340524033283bd2f60b5313f should do the trick -- but try it out on the staging server first to check

**Comment by sandbergja** [comment]
Resolved!
